import type { LoteriaCard } from './types';

const BASE_URL = 'https://placehold.co/200x300.png';

export const LOTERIA_CARDS: LoteriaCard[] = [
  { id: 1, name: { en: 'The Rooster', es: 'El Gallo' }, image: BASE_URL, dataAiHint: "rooster" },
  { id: 2, name: { en: 'The Devil', es: 'El Diablito' }, image: BASE_URL, dataAiHint: "devil" },
  { id: 3, name: { en: 'The Lady', es: 'La Dama' }, image: BASE_URL, dataAiHint: "elegant lady" },
  { id: 4, name: { en: 'The Dandy', es: 'El Catrín' }, image: BASE_URL, dataAiHint: "dandy gentleman" },
  { id: 5, name: { en: 'The Umbrella', es: 'El Paraguas' }, image: BASE_URL, dataAiHint: "umbrella" },
  { id: 6, name: { en: 'The Mermaid', es: 'La Sirena' }, image: BASE_URL, dataAiHint: "mermaid" },
  { id: 7, name: { en: 'The Staircase', es: 'La Escalera' }, image: BASE_URL, dataAiHint: "staircase" },
  { id: 8, name: { en: 'The Bottle', es: 'La Botella' }, image: BASE_URL, dataAiHint: "glass bottle" },
  { id: 9, name: { en: 'The Barrel', es: 'El Barril' }, image: BASE_URL, dataAiHint: "wooden barrel" },
  { id: 10, name: { en: 'The Tree', es: 'El Árbol' }, image: BASE_URL, dataAiHint: "tree" },
  { id: 11, name: { en: 'The Melon', es: 'El Melón' }, image: BASE_URL, dataAiHint: "melon" },
  { id: 12, name: { en: 'The Valiant One', es: 'El Valiente' }, image: BASE_URL, dataAiHint: "valiant man" },
  { id: 13, name: { en: 'The Little Gorilla', es: 'El Gorrito' }, image: BASE_URL, dataAiHint: "bonnet hat" },
  { id: 14, name: { en: 'Death', es: 'La Muerte' }, image: BASE_URL, dataAiHint: "death scythe" },
  { id: 15, name: { en: 'The Pear', es: 'La Pera' }, image: BASE_URL, dataAiHint: "pear" },
  { id: 16, name: { en: 'The Flag', es: 'La Bandera' }, image: BASE_URL, dataAiHint: "mexican flag" },
  { id: 17, name: { en: 'The Bandolón', es: 'El Bandolón' }, image: BASE_URL, dataAiHint: "mandolin" },
  { id: 18, name: { en: 'The Cello', es: 'El Violoncello' }, image: BASE_URL, dataAiHint: "cello" },
  { id: 19, name: { en: 'The Bird', es: 'La Garza' }, image: BASE_URL, dataAiHint: "heron" },
  { id: 20, name: { en: 'The Bird', es: 'El Pájaro' }, image: BASE_URL, dataAiHint: "bird" },
  { id: 21, name: { en: 'The Hand', es: 'La Mano' }, image: BASE_URL, dataAiHint: "hand" },
  { id: 22, name: { en: 'The Boot', es: 'La Bota' }, image: BASE_URL, dataAiHint: "boot" },
  { id: 23, name: { en: 'The Moon', es: 'La Luna' }, image: BASE_URL, dataAiHint: "moon" },
  { id: 24, name: { en: 'The Parrot', es: 'El Cotorro' }, image: BASE_URL, dataAiHint: "parrot" },
  { id: 25, name: { en: 'The Drunk', es: 'El Borracho' }, image: BASE_URL, dataAiHint: "drunk man" },
  { id: 26, name: { en: 'The Apache', es: 'El Negrito' }, image: BASE_URL, dataAiHint: "black man" },
  { id: 27, name: { en: 'The Heart', es: 'El Corazón' }, image: BASE_URL, dataAiHint: "heart" },
  { id: 28, name: { en: 'The Watermelon', es: 'La Sandía' }, image: BASE_URL, dataAiHint: "watermelon" },
  { id: 29, name: { en: 'The Drum', es: 'El Tambor' }, image: BASE_URL, dataAiHint: "drum" },
  { id: 30, name: { en: 'The Shrimp', es: 'El Camarón' }, image: BASE_URL, dataAiHint: "shrimp" },
  { id: 31, name: { en: 'The Ropes', es: 'Las Jaras' }, image: BASE_URL, dataAiHint: "arrows" },
  { id: 32, name: { en: 'The Musician', es: 'El Músico' }, image: BASE_URL, dataAiHint: "musician" },
  { id: 33, name: { en: 'The Spider', es: 'La Araña' }, image: BASE_URL, dataAiHint: "spider" },
  { id: 34, name: { en: 'The Soldier', es: 'El Soldado' }, image: BASE_URL, dataAiHint: "soldier" },
  { id: 35, name: { en: 'The Star', es: 'La Estrella' }, image: BASE_URL, dataAiHint: "star" },
  { id: 36, name: { en: 'The Pot', es: 'El Cazo' }, image: BASE_URL, dataAiHint: "pot" },
  { id: 37, name: { en: 'The World', es: 'El Mundo' }, image: BASE_URL, dataAiHint: "world" },
  { id: 38, name: { en: 'The Apache', es: 'El Apache' }, image: BASE_URL, dataAiHint: "apache" },
  { id: 39, name: { en: 'The Prickly Pear', es: 'El Nopal' }, image: BASE_URL, dataAiHint: "nopal cactus" },
  { id: 40, name: { en: 'The Scorpion', es: 'El Alacrán' }, image: BASE_URL, dataAiHint: "scorpion" },
  { id: 41, name: { en: 'The Rose', es: 'La Rosa' }, image: BASE_URL, dataAiHint: "rose" },
  { id: 42, name: { en: 'The Skull', es: 'La Calavera' }, image: BASE_URL, dataAiHint: "skull" },
  { id: 43, name: { en: 'The Bell', es: 'La Campana' }, image: BASE_URL, dataAiHint: "bell" },
  { id: 44, name: { en: 'The Jug', es: 'El Cantarito' }, image: BASE_URL, dataAiHint: "jug" },
  { id: 45, name: { en: 'The Deer', es: 'El Venado' }, image: BASE_URL, dataAiHint: "deer" },
  { id: 46, name: { en: 'The Sun', es: 'El Sol' }, image: BASE_URL, dataAiHint: "sun" },
  { id: 47, name: { en: 'The Crown', es: 'La Corona' }, image: BASE_URL, dataAiHint: "crown" },
  { id: 48, name: { en: 'The Chalupa', es: 'La Chalupa' }, image: BASE_URL, dataAiHint: "canoe" },
  { id: 49, name: { en: 'The Pine Tree', es: 'El Pino' }, image: BASE_URL, dataAiHint: "pine tree" },
  { id: 50, name: { en: 'The Fish', es: 'El Pescado' }, image: BASE_URL, dataAiHint: "fish" },
  { id: 51, name: { en: 'The Palm Tree', es: 'La Palma' }, image: BASE_URL, dataAiHint: "palm tree" },
  { id: 52, name: { en: 'The Macaw', es: 'La Maceta' }, image: BASE_URL, dataAiHint: "flowerpot" },
  { id: 53, name: { en: 'The Harp', es: 'El Arpa' }, image: BASE_URL, dataAiHint: "harp" },
  { id: 54, name: { en: 'The Frog', es: 'La Rana' }, image: BASE_URL, dataAiHint: "frog" },
];
