import type { LoteriaCard } from './types';

const BASE_URL = 'https://placehold.co/200x300.png';

const fichas = [
  { es: 'abanico', en: 'Fan', hint: 'hand fan' },
  { es: 'acha', en: 'Axe', hint: 'axe' },
  { es: 'anafe', en: 'Stove', hint: 'portable stove' },
  { es: 'ancla', en: 'Anchor', hint: 'anchor' },
  { es: 'árbol', en: 'Tree', hint: 'tree' },
  { es: 'avión', en: 'Airplane', hint: 'airplane' },
  { es: 'bandera', en: 'Flag', hint: 'flag' },
  { es: 'barco', en: 'Boat', hint: 'boat' },
  { es: 'barril', en: 'Barrel', hint: 'barrel' },
  { es: 'botella', en: 'Bottle', hint: 'bottle' },
  { es: 'botuto', en: 'Horn', hint: 'conch shell' },
  { es: 'campana', en: 'Bell', hint: 'bell' },
  { es: 'caracol', en: 'Snail', hint: 'snail' },
  { es: 'casa', en: 'House', hint: 'house' },
  { es: 'cebolla', en: 'Onion', hint: 'onion' },
  { es: 'serrucho', en: 'Saw', hint: 'saw' },
  { es: 'collar', en: 'Necklace', hint: 'necklace' },
  { es: 'copa', en: 'Goblet', hint: 'goblet' },
  { es: 'corona', en: 'Crown', hint: 'crown' },
  { es: 'dado', en: 'Dice', hint: 'dice' },
  { es: 'domino', en: 'Domino', hint: 'domino' },
  { es: 'embudo', en: 'Funnel', hint: 'funnel' },
  { es: 'escalera', en: 'Ladder', hint: 'ladder' },
  { es: 'escoba', en: 'Broom', hint: 'broom' },
  { es: 'estrella', en: 'Star', hint: 'star' },
  { es: 'flecha', en: 'Arrow', hint: 'arrow' },
  { es: 'florero', en: 'Vase', hint: 'flower vase' },
  { es: 'gallina', en: 'Hen', hint: 'hen' },
  { es: 'garza', en: 'Heron', hint: 'heron' },
  { es: 'gato', en: 'Cat', hint: 'cat' },
  { es: 'granada', en: 'Pomegranate', hint: 'pomegranate' },
  { es: 'guitarra', en: 'Guitar', hint: 'guitar' },
  { es: 'hoja', en: 'Leaf', hint: 'leaf' },
  { es: 'lampara', en: 'Lamp', hint: 'lamp' },
  { es: 'lentes', en: 'Glasses', hint: 'glasses' },
  { es: 'libro', en: 'Book', hint: 'book' },
  { es: 'llave', en: 'Key', hint: 'key' },
  { es: 'luna', en: 'Moon', hint: 'moon' },
  { es: 'mango', en: 'Mango', hint: 'mango fruit' },
  { es: 'mano', en: 'Hand', hint: 'hand' },
  { es: 'manzana', en: 'Apple', hint: 'apple' },
  { es: 'maracas', en: 'Maracas', hint: 'maracas' },
  { es: 'mariposa', en: 'Butterfly', hint: 'butterfly' },
  { es: 'mascara', en: 'Mask', hint: 'mask' },
  { es: 'martillo', en: 'Hammer', hint: 'hammer' },
  { es: 'ojo', en: 'Eye', hint: 'eye' },
  { es: 'oreja', en: 'Ear', hint: 'ear' },
  { es: 'pájaro', en: 'Bird', hint: 'bird' },
  { es: 'paraguas', en: 'Umbrella', hint: 'umbrella' },
  { es: 'patilla', en: 'Watermelon', hint: 'watermelon' },
  { es: 'pato', en: 'Duck', hint: 'duck' },
  { es: 'peine', en: 'Comb', hint: 'comb' },
  { es: 'pelota', en: 'Ball', hint: 'ball' },
  { es: 'pescado', en: 'Fish', hint: 'fish' },
  { es: 'pica', en: 'Spade', hint: 'spade' },
  { es: 'pimpina', en: 'Jug', hint: 'jug' },
  { es: 'pipa', en: 'Pipe', hint: 'smoking pipe' },
  { es: 'piña', en: 'Pineapple', hint: 'pineapple' },
  { es: 'pluma', en: 'Feather', hint: 'feather' },
  { es: 'reloj', en: 'Watch', hint: 'watch' },
  { es: 'rosa', en: 'Rose', hint: 'rose' },
  { es: 'zarcillos', en: 'Earrings', hint: 'earrings' },
  { es: 'silla', en: 'Chair', hint: 'chair' },
  { es: 'sombrero', en: 'Hat', hint: 'hat' },
  { es: 'tambor', en: 'Drum', hint: 'drum' },
  { es: 'tasa', en: 'Cup', hint: 'cup' },
  { es: 'tetera', en: 'Teapot', hint: 'teapot' },
  { es: 'tierra', en: 'Earth', hint: 'earth' },
  { es: 'tijeras', en: 'Scissors', hint: 'scissors' },
  { es: 'trébol', en: 'Clover', hint: 'clover' },
  { es: 'tres pelotas', en: 'Three balls', hint: 'three balls' },
  { es: 'trompeta', en: 'Trumpet', hint: 'trumpet' },
  { es: 'trompo', en: 'Spinning top', hint: 'spinning top' },
  { es: 'uvas', en: 'Grapes', hint: 'grapes' },
  { es: 'vaso', en: 'Glass', hint: 'glass' },
  { es: 'berenjena', en: 'Eggplant', hint: 'eggplant' },
  { es: 'zanahoria', en: 'Carrot', hint: 'carrot' },
  { es: 'zapato', en: 'Shoe', hint: 'shoe' },
];

// Remove duplicates and create the final list
const uniqueFichas = fichas.reduce((acc, current) => {
  if (!acc.find(item => item.es === current.es)) {
    acc.push(current);
  }
  return acc;
}, [] as typeof fichas);

export const LOTERIA_CARDS: LoteriaCard[] = uniqueFichas.map((ficha, index) => ({
  id: index + 1,
  name: { en: ficha.en, es: ficha.es },
  image: BASE_URL,
  dataAiHint: ficha.hint,
}));
